### ISSUE TITLE
Steps for merging the ES6 feature into master

### ISSUE THREAD

**Issue by kalwalt** [AR-js-org/AR.js#357]
# Introduction
The ES6 feature #116 is merged into the dev branch. There are some steps to do before merging into master. I found some issues and i think we need to improve the code. I think that is better to face them in small steps than in a BIG PR.

## Things to do

- [x] I found a bug in artoolkit5-js [#11](https://github.com/AR-js-org/artoolkit5-js/issues/11) that make the app crash with a out of memory message.
- [x] ~~add arjs-nft-init-data event to artoolkit5-js and then to AR.js~~ This will be done in another PR.
- [x] Removing not necessary `artoolkit.init()` https://github.com/AR-js-org/AR.js/blob/3bf97f328abdb94a4cc34240edca8cc26a5fcad1/three.js/src/threex/arjs-context.js#L208 because it is already initied inside the ARController `_initialize` https://github.com/AR-js-org/artoolkit5-js/blob/aa21c379d51b08e9a0d52b26f9f6928084ddb844/src/ARController.js#L1260
- [x] Pattern examples works differently on Mobile devices, differences between Aframe and Threex. This happens because we not provide to the arController the right 'orientation'. Fixed in PR #359
- [x] Three.js location based integration (dist bundle.js missed?)
- [x] ~~OnResize should be optional?~~ This will be done in another PR or at least need some discussion in an issue. 
- [x] ~~OnResize could be injected?~~ This will be done in another PR or at least need some discussion in an issue. 
- [x] ~~Threex should be in a different package?~~ Same as above.
- [x] passing only ImageData to `_copyImageToHeap(sourceImage)` see discussion here https://github.com/AR-js-org/AR.js/discussions/266
- [x] fix some three.js marker examples with the new orientation routine.
- [x] fix bug with labelingMode (white_markers) see #384
- [x] update README about npm package, with minimal infos (how to install and use)

I will update this list, i hope to not enlarge too much...

**Comment by kalwalt** [comment]
@nickw1 just a quick question: There is no bundled file in the `three.js location based` (TLB) folder. This is intentionally because is experimental? or we can find a kind of integration? I'm asking this for the npm package, actually TLB can't not be used as a npm package in the `@ar-js-org/ar.js` distribution. Just thinking how to proceed.

**Comment by nickw1** [comment]
@kalwalt yes, Yes you're right, there is no bundle. This was due to it being experimental; however I can build one.

**Comment by nickw1** [comment]
@kalwalt ok I have fixed it to build a bundle, the bundle is in the repo. However this is using my own webpack build script rather than the build script for the whole AR.js source code. Shall I leave it up to you to integrate it with the rest of the build?

**Comment by kalwalt** [comment]
> @kalwalt yes, Yes you're right, there is no bundle. This was due to it being experimental; however I can build one.

ok I can do it, don't worry. Just asking for clearity. I will try it and maybe i can find to integate into threex.

Right now i'm working on the marker examples. They looks different (i'm testing on Mobile devices), Three.js examples in dev branch are displayed ok in portrait and landscape mode, but Aframe examples looks wierd in portrait and good in landscape. ANd when i say the y looks wierd i mean that the ube or the mesh is kewed or not perfectly alligned to the marker.
I have this [branch](https://github.com/AR-js-org/AR.js/tree/testing-artoolkit5-js-imp) where i'm testing a diffeent approach wit a modified `_copyImageToHeap` inside artoolkit5-js.

**Comment by kalwalt** [comment]
> @kalwalt ok I have fixed it to build a bundle, the bundle is in the repo. However this is using my own webpack build script rather than the build script for the whole AR.js source code. Shall I leave it up to you to integrate it with the rest of the build?

yes thank you!

**Comment by wd40bomber7** [comment]
I'm on the latest developer version and I'm hitting a problem where everything works great on desktop, but on mobile the cube's orientation is constantly wrong and jumps around. Is this a known issue?

**Comment by kalwalt** [comment]
> I'm on the latest developer version and I'm hitting a problem where everything works great on desktop, but on mobile the cube's orientation is constantly wrong and jumps around. Is this a known issue?

Yes i know, as i said in a comment above and on the top of the thread. I'm testing now this [branch](https://github.com/AR-js-org/AR.js/tree/testing-artoolkit5-js-imp) if you want to take a look at. But be aware it's not completely solved. Try only the `three.js/examples/minimal_ES6.html` and `aframe/examples/marker-based/minimal_ES6.html`. I will open a WIP PR very soon.

**Comment by wd40bomber7** [comment]
Ah sorry, I didn't quite understand what "Pattern differences working differently" meant. I'll keep my eyes out for the WIP PR. Thank you!

**Comment by kalwalt** [comment]
> Ah sorry, I didn't quite understand what "Pattern differences working differently" meant. I'll keep my eyes out for the WIP PR. Thank you!

No problem, my fault i sould explain better the issue.
The issue (with mobile devices) is more on the Aframe side. Meshes in Three.js examples looks correctly (not skewed and placed correctly onto the marker). @wd40bomber7 can you confirm this?

**Comment by kalwalt** [comment]
I think i have fixed the aframe marker examples, can someone test please the code in PR #359? You can test these examples: `marker-camera.html`, `marker-events.html`, `minimal_ES6.html`, `minimal.html`, `multiple-independent-markers.html` and `white-region-marker.html`.
I think we are close to merge it in the dev branch!

**Comment by kalwalt** [comment]
I also removed some tasks because i think we can do them in another PRs, does not make sense postpone to merge the ES6 feature again. All that changes/improvements can be done after, we need to close this and go ahead.

**Comment by kalwalt** [comment]
Fixed bug with white region markers with commit https://github.com/AR-js-org/AR.js/commit/99bda004452549e8a7576b9e7afc26992aa0104e see #384. That was fixed also in master branch https://github.com/AR-js-org/AR.js/commit/99bda004452549e8a7576b9e7afc26992aa0104e

**Comment by kalwalt** [comment]
#359 has been merged in dev. I think now we need only to fix some small bugs and improve/update the Readme and the documentation and we are ready to merge ES6 feature into master!

**Comment by kalwalt** [comment]
**ES6** feature merged into master #400
